version: "3"

services:
  ### API #############################
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    env_file: 
      - .env.dev
    ports:
      - "4000:4000"
    expose:
      - "4000"
    volumes:
      # Binds the application folder from the host inside the container for fast changes
      - ./api:/app
      # Ignores/Hides the node_modules from the bind on the host allowing the node_modules
      # from inside the container to be used instead
      - /app/node_modules
    depends_on:
      - postgres
    networks:
      - backend

  ### Database #############################
  postgres:
    build:
      context: ./.docker/postgres
    env_file: 
      - .env.dev
    ports:
      - "5435:5432"
    env_file:
      - .env.dev
    environment:
      - POSTGRES_MULTIPLE_DATABASES="nest_api_dev","nest_api_test","court_migrations"
      - POSTGRES_USER=court_nestapi
      - POSTGRES_PASSWORD=court_nest123
    networks:
      - backend

  ### Frontend ###############################
  client:
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
    env_file: 
      - .env.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "35729:35729"
      - "3000:3000"
    stdin_open: true
    networks:
      - backend
    depends_on:
      - api

networks:
  backend:
    driver: "bridge"

volumes:
  postgres:
