version: "3"

services:
  ### API ###################################
  api:
    image: court-nest-api:dev
    container_name: court-nest
    stdin_open: true
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    expose:
      - "4000"
    volumes:
      # Binds the application folder from the host inside the container for fast changes
      - ./api:/app
      # Ignores/Hides the node_modules from the bind on the host allowing the node_modules
      # from inside the container to be used instead
      - /app/node_modules
    depends_on:
      - postgres
    networks:
      - backend

  ### Database ##############################
  postgres:
    image: court-nest-api-postgres:dev
    container_name: court-nest-api-database
    build:
      context: ./.docker/postgres
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_MULTIPLE_DATABASES="nest_api_dev","nest_api_test","court_migrations"
      # ,"sonar"
      - POSTGRES_USER=court_nestapi
      - POSTGRES_PASSWORD=court_nest123
    networks:
      - backend

  ### Frontend ##############################
  client:
    image: court-frontend:dev
    container_name: court-frontend
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
      args:
        REACT_APP_REALM_AUTH_URL: https://oidc.gov.bc.ca/auth
        REACT_APP_API_HOST: https://court-interpreter-scheduling.apps.silver.devops.gov.bc.ca/api/v1
    ports:
      - "8888:5000"
    expose:
      - "8888"
    networks:
      - backend

networks:
  backend:
    driver: "bridge"

volumes:
  postgres:
