version: "3"

services:
  ### API ###################################
  api:
    image: court-nest-api:dev
    container_name: court-nest
    stdin_open: true
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file: 
      - .env.test
    ports:
      - "4000:4000"
    expose:
      - "4000"
    volumes:
      # Binds the application folder from the host inside the container for fast changes
      - ./api:/usr/src/app
      # Ignores/Hides the node_modules from the bind on the host allowing the node_modules
      # from inside the container to be used instead
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    networks:
      backend:
        aliases:
          - api.local.freshworks.club

  ### Database ##############################
  postgres:
    image: court-nest-api-postgres:dev
    container_name: court-nest-api-database
    build:
      context: ./.docker/postgres
    env_file: 
      - .env.test
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_MULTIPLE_DATABASES="nest_api_dev","nest_api_test","court_migrations"
      - POSTGRES_USER=court_nestapi
      - POSTGRES_PASSWORD=court_nest123
    networks:
      - backend

  ### Frontend ##############################
  client:
    image: client
    container_name: client
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
      args:
        REACT_APP_REALM_AUTH_URL: https://test.oidc.gov.bc.ca/auth
        REACT_APP_API_HOST: https://test-court-interpreter-scheduling.apps.silver.devops.gov.bc.ca/api/v1
        REACT_APP_KC_REALM: cis-web
    env_file: 
      - .env.test
    restart: always
    ports:
      - "5000:5000"
    expose:
      - "5000"
    networks:
      - backend

networks:
  backend:
    driver: "bridge"

volumes:
  postgres:
